name: Converti Storico Lotto in JSON

on:
  push:
    paths:
      - 'storico.txt' # Il processo parte solo quando modifichi questo file

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Controlla il codice del repository
      uses: actions/checkout@v4

    - name: Configura Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Esegui il convertitore
      run: python convertitore.py

    - name: Salva e pubblica il file JSON modificato
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add estrazioni_complete.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Aggiornato file estrazioni_complete.json in automatico" && git push)
